version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  prometheus_nginx:                                                                                                   
    image: nginx/nginx-prometheus-exporter:0.9.0                                                                      
    ports:                                                                                                            
    - "9113:9113"                                                                                                     
    command:                                                                                                          
    - -nginx.scrape-uri                                                                                               
    - http://demo.nginx.com/stub_status   

volumes:
  prometheus-data:
  alertmanager-data:  